# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ deps: "
