/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 * Generated by: https://openapi-generator.tech
 */

/// Errors : Information about the errors.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Errors {
    /// The code of the error.
    #[serde(rename = "Code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// The details of the error.
    #[serde(rename = "Details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// The type of the error.
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl Errors {
    /// Information about the errors.
    pub fn new() -> Errors {
        Errors {
            code: None,
            details: None,
            _type: None,
        }
    }
}
