/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.22
 * Contact: support@outscale.com
 * Generated by: https://openapi-generator.tech
 */

/// QuotaTypes : One or more quotas.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QuotaTypes {
    /// The resource ID if it is a resource-specific quota, `global` if it is not.
    #[serde(rename = "QuotaType", skip_serializing_if = "Option::is_none")]
    pub quota_type: Option<String>,
    /// One or more quotas associated with the user.
    #[serde(rename = "Quotas", skip_serializing_if = "Option::is_none")]
    pub quotas: Option<Vec<crate::models::Quota>>,
}

impl QuotaTypes {
    /// One or more quotas.
    pub fn new() -> QuotaTypes {
        QuotaTypes {
            quota_type: None,
            quotas: None,
        }
    }
}
