/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://wiki.outscale.net/display/EN/3DS+OUTSCALE+APIs+Reference).<br /><br />  You can also manage your resources using the [Cockpit](https://wiki.outscale.net/display/EN/About+Cockpit) web interface.
 *
 * The version of the OpenAPI document: 1.16
 * Contact: support@outscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateNetAccessPointRequest {
    /// One or more IDs of route tables to associate with the specified Net access point.
    #[serde(rename = "AddRouteTableIds", skip_serializing_if = "Option::is_none")]
    pub add_route_table_ids: Option<Vec<String>>,
    /// If true, checks whether you have the required permissions to perform the action.
    #[serde(rename = "DryRun", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    /// The ID of the Net access point.
    #[serde(rename = "NetAccessPointId")]
    pub net_access_point_id: String,
    /// One or more IDs of route tables to disassociate from the specified Net access point.
    #[serde(
        rename = "RemoveRouteTableIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub remove_route_table_ids: Option<Vec<String>>,
}

impl UpdateNetAccessPointRequest {
    pub fn new(net_access_point_id: String) -> UpdateNetAccessPointRequest {
        UpdateNetAccessPointRequest {
            add_route_table_ids: None,
            dry_run: None,
            net_access_point_id,
            remove_route_table_ids: None,
        }
    }
}
