/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://wiki.outscale.net/display/EN/3DS+OUTSCALE+APIs+Reference).<br /><br />  You can also manage your resources using the [Cockpit](https://wiki.outscale.net/display/EN/About+Cockpit) web interface.
 *
 * The version of the OpenAPI document: 1.16
 * Contact: support@outscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateSnapshotRequest {
    /// If true, checks whether you have the required permissions to perform the action.
    #[serde(rename = "DryRun", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    #[serde(rename = "PermissionsToCreateVolume")]
    pub permissions_to_create_volume: Box<crate::models::PermissionsOnResourceCreation>,
    /// The ID of the snapshot.
    #[serde(rename = "SnapshotId")]
    pub snapshot_id: String,
}

impl UpdateSnapshotRequest {
    pub fn new(
        permissions_to_create_volume: crate::models::PermissionsOnResourceCreation,
        snapshot_id: String,
    ) -> UpdateSnapshotRequest {
        UpdateSnapshotRequest {
            dry_run: None,
            permissions_to_create_volume: Box::new(permissions_to_create_volume),
            snapshot_id,
        }
    }
}
