name: osc-sdk-rust crate.io publishing
on:
  release:
    types: [released]

jobs:
  publish:
    environment: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Stable Rust with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - name: Cargo publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
