name: pull-request

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write
  id-token: write
    
jobs:
  reuse-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Reuse specification test
        run: make reuse-test
  examples-test:
    runs-on: [authenticated, Linux]
    steps:
      - name: 🔒🧹 Setup Vault & Frieza
        id: secrets
        uses: outscale/.github/vault-frieza-clean@eb7bd1e0360703d0ad355bce46029ae8d49bac04
        with:
          vault_role: outscale-osc-sdk-rust
          osc_account: oak
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Stable Rust with rustfmt
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt
      - name: local tests
        run: ./local_tests.sh
      - name: Run examples
        if: "! contains(github.event.pull_request.labels.*.name, 'dependencies')"
        env:
          OSC_ACCESS_KEY: ${{ steps.secrets.outputs.access_key }}
          OSC_SECRET_KEY: ${{ steps.secrets.outputs.secret_key }}
          OSC_REGION: ${{ steps.secrets.outputs.region }}
        run: make examples-test
  regeneration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Stable Rust with rustfmt
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt
      - name: SDK re-generation test
        run: make regen-test
