name: pull-request

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write
  id-token: write
    
jobs:
  reuse-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Reuse specification test
        run: make reuse-test
  examples-test:
    runs-on: [authenticated, Linux]
    steps:
      - name: 🔒🧹 Setup Vault & Frieza
        id: secrets
        uses: outscale/.github/vault-frieza-clean@eb7bd1e0360703d0ad355bce46029ae8d49bac04
        with:
          vault_role: outscale-osc-sdk-rust
          osc_account: oak
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Stable Rust with rustfmt
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          components: rustfmt
      - name: local tests
        run: ./local_tests.sh
      - name: Run examples
        if: "! contains(github.event.pull_request.labels.*.name, 'dependencies')"
        env:
          OSC_ACCESS_KEY: ${{ steps.secrets.outputs.access_key }}
          OSC_SECRET_KEY: ${{ steps.secrets.outputs.secret_key }}
          OSC_REGION: ${{ steps.secrets.outputs.region }}
        run: make examples-test
  regeneration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Stable Rust with rustfmt
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          components: rustfmt
      - name: SDK re-generation test
        run: make regen-test
